// <auto-generated />
using System;
using IndustrialMonitor.Alarm;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndustrialMonitor.Alarm.Migrations
{
    [DbContext(typeof(AlarmDbContext))]
    partial class AlarmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("IndustrialMonitor.Alarm.Models.AlarmRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmItem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecovered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecoveredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("AlarmRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
