// <auto-generated />
using System;
using IndustrialMonitor.Core.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndustrialMonitor.Core.Migrations
{
    [DbContext(typeof(IndustrialMonitorDbContext))]
    [Migration("20260704183026_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndustrialMonitor.Core.Models.DeviceDataModel", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("value00")
                        .HasColumnType("int");

                    b.Property<int>("value01")
                        .HasColumnType("int");

                    b.Property<int>("value02")
                        .HasColumnType("int");

                    b.Property<int>("value03")
                        .HasColumnType("int");

                    b.Property<int>("value04")
                        .HasColumnType("int");

                    b.Property<int>("value05")
                        .HasColumnType("int");

                    b.Property<int>("value06")
                        .HasColumnType("int");

                    b.Property<int>("value07")
                        .HasColumnType("int");

                    b.Property<int>("value08")
                        .HasColumnType("int");

                    b.Property<int>("value09")
                        .HasColumnType("int");

                    b.Property<int>("value10")
                        .HasColumnType("int");

                    b.Property<int>("value11")
                        .HasColumnType("int");

                    b.Property<int>("value12")
                        .HasColumnType("int");

                    b.Property<int>("value13")
                        .HasColumnType("int");

                    b.Property<int>("value14")
                        .HasColumnType("int");

                    b.Property<int>("value15")
                        .HasColumnType("int");

                    b.Property<int>("value16")
                        .HasColumnType("int");

                    b.Property<int>("value17")
                        .HasColumnType("int");

                    b.Property<int>("value18")
                        .HasColumnType("int");

                    b.Property<int>("value19")
                        .HasColumnType("int");

                    b.Property<int>("value20")
                        .HasColumnType("int");

                    b.Property<int>("value21")
                        .HasColumnType("int");

                    b.Property<int>("value22")
                        .HasColumnType("int");

                    b.Property<int>("value23")
                        .HasColumnType("int");

                    b.Property<int>("value24")
                        .HasColumnType("int");

                    b.Property<int>("value25")
                        .HasColumnType("int");

                    b.Property<int>("value26")
                        .HasColumnType("int");

                    b.Property<int>("value27")
                        .HasColumnType("int");

                    b.Property<int>("value28")
                        .HasColumnType("int");

                    b.Property<int>("value29")
                        .HasColumnType("int");

                    b.HasKey("DeviceId");

                    b.ToTable("DeviceDataModels");
                });
#pragma warning restore 612, 618
        }
    }
}
