<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IndustrialMonitor.Communication\IndustrialMonitor.Communication.csproj" />
    <ProjectReference Include="..\IndustrialMonitor.Core\IndustrialMonitor.Core.csproj" />
  </ItemGroup>

</Project>
